from __future__ import annotations

import io
from datetime import datetime
from pathlib import Path
from typing import Any

from PIL import Image, ImageOps, UnidentifiedImageError
from pypdf import PdfReader, PdfWriter
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


class PDFGenerationError(ValueError):
    def __init__(self, public_message: str) -> None:
        super().__init__(public_message)
        self.public_message = public_message


def generate_customer_approval_pdf(
    *,
    template_path: Path,
    output_dir: Path,
    form_data: dict[str, Any],
    customer_signature_bytes: bytes,
    technician_signature_bytes: bytes,
) -> dict[str, Any]:
    if not form_data.get("job_number"):
        raise PDFGenerationError("Job number is required to generate the PDF.")

    template_path = Path(template_path)
    output_dir = Path(output_dir)

    if not template_path.exists():
        raise PDFGenerationError(
            f"PDF template file was not found: {template_path}"
        )

    if template_path.suffix.lower() != ".pdf":
        raise PDFGenerationError("PDF template path is invalid.")

    try:
        output_dir.mkdir(parents=True, exist_ok=True)
    except Exception as error:
        raise PDFGenerationError("Could not create the PDF output directory.") from error

    customer_signature_png = _normalize_signature_image(customer_signature_bytes, "customer")
    technician_signature_png = _normalize_signature_image(technician_signature_bytes, "technician")

    file_stem = _safe_filename(
        f"customer-approval-{form_data.get('job_number', 'document')}-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"
    )
    output_path = output_dir / f"{file_stem}.pdf"

    overlay_buffer = io.BytesIO()

    try:
        pdf = canvas.Canvas(overlay_buffer, pagesize=LETTER)
        width, height = LETTER

        pdf.setTitle("Customer Approval")
        pdf.setAuthor("Customer Approval App")

        pdf.setFillColor(HexColor("#F4F7FB"))
        pdf.rect(0, 0, width, height, fill=1, stroke=0)

        pdf.setFillColor(HexColor("#102033"))
        pdf.setFont("Helvetica-Bold", 20)
        pdf.drawString(48, height - 56, "Customer Approval")
        pdf.setFont("Helvetica", 10)
        pdf.setFillColor(HexColor("#617188"))
        pdf.drawString(48, height - 74, "Generated by Customer Approval App")

        sections = [
            (
                "Job Details",
                [
                    ("Job Number", _clean_text(form_data.get("job_number", ""))),
                    ("Installation Date", _clean_text(form_data.get("installation_date", ""))),
                ],
            ),
            (
                "Customer Details",
                [
                    ("Customer Name", _clean_text(form_data.get("customer_name", ""))),
                    ("Service Address", _clean_text(form_data.get("service_address", ""))),
                    ("City, State, ZIP", _clean_text(form_data.get("city_state_zip", ""))),
                    ("Primary Phone", _clean_text(form_data.get("phone_number", ""))),
                    ("Work Phone", _clean_text(form_data.get("work_phone_number", ""))),
                    ("Email", _clean_text(form_data.get("email", ""))),
                ],
            ),
            (
                "Technician Details",
                [
                    ("Technician Name", _clean_text(form_data.get("technician_name", ""))),
                ],
            ),
        ]

        top = height - 112
        for title, rows in sections:
            top = _draw_section(pdf, title, rows, top)

        top -= 8
        pdf.setFont("Helvetica-Bold", 11)
        pdf.setFillColor(HexColor("#102033"))
        pdf.drawString(48, top, "Signatures")
        top -= 16

        _draw_signature_block(
            pdf,
            x=48,
            y=top - 88,
            label="Customer Signature",
            signature_bytes=customer_signature_png,
        )
        _draw_signature_block(
            pdf,
            x=320,
            y=top - 88,
            label="Technician Signature",
            signature_bytes=technician_signature_png,
        )

        pdf.showPage()
        pdf.save()
        overlay_buffer.seek(0)
    except PDFGenerationError:
        raise
    except Exception as error:
        raise PDFGenerationError("Unable to draw the approval PDF.") from error

    final_bytes = _merge_with_template(template_path=template_path, overlay_bytes=overlay_buffer.getvalue())

    try:
        output_path.write_bytes(final_bytes)
    except Exception as error:
        raise PDFGenerationError("Unable to save the generated PDF file.") from error

    return {
        "filename": output_path.name,
        "path": str(output_path),
        "bytes": final_bytes,
    }


def _normalize_signature_image(signature_bytes: bytes, role: str) -> bytes:
    if not signature_bytes:
        raise PDFGenerationError(f"The {role} signature is empty.")

    try:
        with Image.open(io.BytesIO(signature_bytes)) as source:
            normalized = ImageOps.exif_transpose(source)
            if normalized.mode not in ("RGBA", "LA"):
                normalized = normalized.convert("RGBA")

            bbox = normalized.getbbox()
            if bbox:
                normalized = normalized.crop(bbox)

            max_width = 900
            max_height = 240
            normalized.thumbnail((max_width, max_height))

            output = io.BytesIO()
            normalized.save(output, format="PNG")
            return output.getvalue()
    except UnidentifiedImageError as error:
        raise PDFGenerationError(f"The {role} signature image is invalid.") from error
    except Exception as error:
        raise PDFGenerationError(f"Unable to process the {role} signature.") from error


def _draw_section(pdf: canvas.Canvas, title: str, rows: list[tuple[str, str]], top: float) -> float:
    pdf.setFillColor(HexColor("#FFFFFF"))
    height = 34 + (len(rows) * 24)
    pdf.roundRect(40, top - height, 532, height, 18, fill=1, stroke=0)

    pdf.setFillColor(HexColor("#102033"))
    pdf.setFont("Helvetica-Bold", 11)
    pdf.drawString(56, top - 22, title)

    current_y = top - 42
    for label, value in rows:
        pdf.setFont("Helvetica-Bold", 9)
        pdf.setFillColor(HexColor("#617188"))
        pdf.drawString(56, current_y, label.upper())

        pdf.setFont("Helvetica", 11)
        pdf.setFillColor(HexColor("#102033"))
        pdf.drawString(180, current_y, value or "-")
        current_y -= 24

    return top - height - 16


def _draw_signature_block(pdf: canvas.Canvas, *, x: float, y: float, label: str, signature_bytes: bytes) -> None:
    pdf.setFillColor(HexColor("#FFFFFF"))
    pdf.roundRect(x, y, 224, 96, 18, fill=1, stroke=0)

    pdf.setFillColor(HexColor("#617188"))
    pdf.setFont("Helvetica-Bold", 9)
    pdf.drawString(x + 14, y + 78, label.upper())

    pdf.setStrokeColor(HexColor("#617188"))
    pdf.line(x + 14, y + 24, x + 210, y + 24)

    try:
        pdf.drawImage(
            ImageReader(io.BytesIO(signature_bytes)),
            x + 18,
            y + 30,
            width=188,
            height=40,
            preserveAspectRatio=True,
            mask="auto",
        )
    except Exception as error:
        raise PDFGenerationError(f"Unable to render {label.lower()}.") from error


def _merge_with_template(*, template_path: Path, overlay_bytes: bytes) -> bytes:
    try:
        template_reader = PdfReader(str(template_path))
    except Exception as error:
        raise PDFGenerationError("Unable to open the PDF template.") from error

    try:
        overlay_reader = PdfReader(io.BytesIO(overlay_bytes))
    except Exception as error:
        raise PDFGenerationError("Unable to read the generated PDF overlay.") from error

    if not template_reader.pages:
        raise PDFGenerationError("The PDF template has no pages.")

    if not overlay_reader.pages:
        raise PDFGenerationError("The generated overlay has no pages.")

    try:
        writer = PdfWriter()

        first_page = template_reader.pages[0]
        first_page.merge_page(overlay_reader.pages[0])
        writer.add_page(first_page)

        for page in template_reader.pages[1:]:
            writer.add_page(page)

        output = io.BytesIO()
        writer.write(output)
        return output.getvalue()
    except Exception as error:
        raise PDFGenerationError("Unable to apply the PDF template.") from error


def _clean_text(value: Any) -> str:
    return str(value or "").strip()


def _safe_filename(value: str) -> str:
    cleaned = "".join(
        character if character.isalnum() or character in {"-", "_"} else "-"
        for character in value
    ).strip("-")
    return cleaned or "customer-approval"
